server:
  port: 8080
  ssl:
    key-alias: selfsigned_localhost_sslserver
    key-password: changeit
    key-store: classpath:ssl-server.jks
    key-store-provider: SUN
    key-store-type: JKS
  
spring:
  profiles: test
  data:
    mongodb:
      database: test12
      host: localhost
      port: 27017
      
name: test-YAML
environment: test
servers: 
    - www.abc.test.com
    - www.xyz.test.com
    
    
  
  